language: python
matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7
        - python: 3.8
        - python: 3.8
          services:
              - docker
          env: BUILD_SDIST=true
        - name: Python 3.6.9 on macOS
          os: osx
          language: objective-c
          env: PYENV_VERSION=3.6.9
        - name: Python 3.7.5 on macOS
          os: osx
          osx_image: xcode11.3
          language: objective-c
          env: PYENV_VERSION=3.7.5
        - name: Python 3.8.0 on macOS
          os: osx
          osx_image: xcode11.3
          language: objective-c
          env: PYENV_VERSION=3.8.0
install:
    - pip install -U tox-travis
    - pip install -e ."[all]"
    - pip install -e ."[test]"
script:
    - python setup.py test
after_script:
    - bash scripts/deploy.sh
after_success:
    - pip install coveralls
    - coveralls
